#!/bin/bash
####################################################
# This script is automatically generated by the GUI./ replaced using updater class
# It contains the setting of the current working directory and launching of the run_exp.sh
###################################################
qqqqq


cd D:\projects\abm\GUI_DEV
bash run_exp.sh


