#!/bin/bash
####################################################
# This script is automatically generated by the GUI.
# It is for setting up and running the experiment:
# Steps:
# - 1 : experiment settings
# - 2 : creation of experiment folder hierarchy
# - 3 : creation of the specific settings xml file
# - 4 : creation of a job list
# - 5 : launching the job list
# - 6 : start plotting routines using R
	################################################################################################################


#Set the base folder
export BASE='D:\projects\abm\GUI_DEV'




#0.xml file
export ZERO_XML_FILE='D:\projects\abm\GUI_DEV\EuraceUnibi_Model_1.0\its\0_after_2k_transient.xml'
#Export the database folder for R scripts
export DATABASE_LOCATION='D:\projects\abm\GUI_DEV'


#Iterations
export ITS=5000


#Set number of nodes to use (only valid for parallel)
export NR_NODES=1


#Set number of job processes to use (nr of job lists: job_list_$n.sh)
export NUM_PROCS=1


#Set the number of parameters to vary
export NUM_PARS=0


#Set number of batch runs
export TOTAL_RUNS=10
export RUNS=$(seq 1 $TOTAL_RUNS)
echo 'Batch runs:[' $RUNS ']'


#Executables
export MAIN_S='.'


#Location of the model XML (used to generate the SQL)
export MODEL_XML_FILE='D:\projects\abm\GUI_DEV\EuraceUnibi_Model_1.0\eurace_model.xml'


#Location of R scripts
#Parallel
export PATH_R_SCRIPTS='./Data_Analysis_GUI_Serial/'


#Running simulations
export DO_RUN=1
export CREATE_SQL=1


#Compress the database, keeping the original .db file. If a pre-existing compressed file exists, overwrite and recreate it.
export DO_COMPRESS_KEEP_ORIGINAL=0


#Compress the database, remove the original .db file. If a pre-existing compressed file exists, overwrite and recreate it.
export DO_COMPRESS_REMOVE_ORIGINAL=0


#Decompress the SQL database without removing the original compressed file
export DO_DECOMPRESS=0


#Remove the decompressed files
export DO_REMOVE_DB=0


echo 'Starting top-level experiment script...'


######### STEP 1: EXPERIMENT SETTINGS ##################################################################
. set_exp.sh


######### STEP 2: CREATION OF EXPERIMENT FOLDER HIERARCHY 
bash ./exp_script_1_setup.sh


######### STEP 3: CREATION OF THE SPECIFIC SETTINGS XML FILE 
bash ./exp_script_2_specific.sh


######### STEP 4: CREATING  JOB SCRIPTS 
bash ./create_job_list.sh


######### STEP 5: LAUNCHING  JOB SCRIPTS 
bash ./launch_job_list.sh


wait
######### STEP 6: R scripts for plotting data
# Parallel R
bash ./r_serial.sh


wait
######### STEP 7: Compress dara bases
bash ./create_job_list_compress.sh


bash ./launch_job_list.sh


echo 'Finished top-level experiment script.'


